language: python
python:
- '3.6'
sudo: false
cache: pip3
install:
- pip3 install -r requirements.txt
- pip3 install coverage
- pip3 install coveralls
before_script:
  - "psql -c 'create database authentication;' -U postgres"
script:
- pytest --cov=api
- coverage report
after_success:
- coveralls